/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-06 12:31:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.community.model.vo.*;
import com.kh.common.model.vo.PageInfo;
import com.kh.user.model.vo.*;
import com.kh.user.model.vo.Hospital;

public final class CommunityListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/community/../common/menubar.jsp", Long.valueOf(1657091418207L));
    _jspx_dependants.put("/views/community/../common/footer.jsp", Long.valueOf(1657091418206L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.kh.community.model.vo");
    _jspx_imports_packages.add("com.kh.user.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.user.model.vo.Hospital");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Community> list = (ArrayList<Community>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");	
	
	// 페이징바 만들 때 필요한 변수 미리 셋팅
	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petist-게시글 목록</title>\r\n");
      out.write("<link href=\"/Petist/resources/common/logo_mint.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<style>   \r\n");
      out.write("      \r\n");
      out.write("   #communityPageMenu {\r\n");
      out.write("      font-size: 27px;\r\n");
      out.write("      font-weight:bolder;\r\n");
      out.write("      border-bottom: 1px solid black;\r\n");
      out.write("      width: 150px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: rgb(26, 188, 156);\r\n");
      out.write("      margin-top: 25px;\r\n");
      out.write("   }   \r\n");
      out.write("   .nav{\r\n");
      out.write("      width: 160px;\r\n");
      out.write("      margin: 15px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("   }\r\n");
      out.write("   #selectMem th{\r\n");
      out.write("      background-color: lightgrey;\r\n");
      out.write("   }\r\n");
      out.write("   #management, #notice, #board {\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write("   #chat,#questionboard{\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color:black;\r\n");
      out.write("      text-decoration-line: none;\r\n");
      out.write("      text-decoration-color: black;\r\n");
      out.write("   }\r\n");
      out.write("   li>a{\r\n");
      out.write("      color: black;\r\n");
      out.write("   }\r\n");
      out.write("   li{\r\n");
      out.write("      list-style-type: none;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("   }\r\n");
      out.write("   .content_2{\r\n");
      out.write("      padding-left:150px;\r\n");
      out.write("      padding-top: 90px;\r\n");
      out.write("   }\r\n");
      out.write("   #reachMem{\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("   }\r\n");
      out.write("   table{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      border:1px solid lightgray;\r\n");
      out.write("      width:810px;\r\n");
      out.write("  \r\n");
      out.write("   }\r\n");
      out.write("   table td{\r\n");
      out.write("         text-align:left;\r\n");
      out.write("         vertical-align: top;\r\n");
      out.write("         \r\n");
      out.write("   }\r\n");
      out.write("   table th{\r\n");
      out.write("         height:30px;\r\n");
      out.write("   }\r\n");
      out.write("   .listButton{\r\n");
      out.write("      padding-top: 40px;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("    .paging-area{\r\n");
      out.write("      padding-top: 40px;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write(".list-area>tbody>tr:hover{\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        background-color: gray;\r\n");
      out.write(" }\r\n");
      out.write(" 	\r\n");
      out.write(" 	.wagle {\r\n");
      out.write(" 		font-weight:bold;\r\n");
      out.write(" 	}\r\n");
      out.write(" 	\r\n");
      out.write(" 	.question{\r\n");
      out.write(" 		font-weight:bold;\r\n");
      out.write(" 	}\r\n");
      out.write(" 	\r\n");
      out.write(" 	.llist>td {\r\n");
      out.write(" 	\r\n");
      out.write(" 	text-align : center;\r\n");
      out.write(" 	}\r\n");
      out.write(" 	\r\n");
      out.write(" 	#writeBtn {\r\n");
      out.write(" 		margin-left:750px\r\n");
      out.write(" 	}\r\n");
      out.write(" 	\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	Hospital loginHosp = (Hospital)session.getAttribute("loginHosp");

	String alertMsg = (String)session.getAttribute("alertMsg");
	
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    .nav-area { background-color: rgb(26, 188, 156); height: 78px; }\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        height: 76px;\r\n");
      out.write("        width: auto;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a, .menu button {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 16px; \r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu button {\r\n");
      out.write("        background-color: rgb(26, 188, 156);\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #logo:hover { cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write("    #petist { \r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        vertical-align: center;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    #photo {\r\n");
      out.write("        padding-left: 15px;\r\n");
      out.write("        padding-right: 15px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu a:hover { text-decoration: underline; text-underline-position: under; text-decoration-thickness: 4px; font-size: 18px; }\r\n");
      out.write("\r\n");
      out.write("    .last { padding-right: 40px; padding-left: 40px; }\r\n");
      out.write("\r\n");
      out.write("    img { width: 55px; height: 55px; }\r\n");
      out.write("    \r\n");
      out.write("    div {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .content {\r\n");
      out.write("    	width: 1200px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content > div, .content_short > div {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        margin-bottom: 30px;    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content_short {\r\n");
      out.write("    	width: 1200px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content_1 {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    .content_2 {\r\n");
      out.write("    	width: 80%;\r\n");
      out.write("    }\r\n");
      out.write("    .content_3 {\r\n");
      out.write("    	width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    div {\r\n");
      out.write("    	box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("		\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\"){\r\n");
      out.write("			Swal.fire({\r\n");
      out.write("				  title: 'Petist',\r\n");
      out.write("				  text: msg,\r\n");
      out.write("				  imageUrl: '/Petist/resources/common/logo_mint.png',\r\n");
      out.write("				  imageWidth: 130,\r\n");
      out.write("				  imageHeight: 110,\r\n");
      out.write("				  confirmButtonText: '확인',\r\n");
      out.write("				  confirmButtonColor: '#1abc9c'\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"nav-area\" align=\"right\">\r\n");
      out.write("        <div class=\"menu\" id=\"logo\" style=\"float:left;\" onclick='location.href=\"");
      out.print( contextPath );
      out.write("\";'>\r\n");
      out.write("            <div class=\"menu\" id=\"photo\">\r\n");
      out.write("                <img src=\"/Petist/resources/common/logo.png\" alt=\"로고\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <span id=\"petist\" class=\"menu\">Petist</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("\">HOME</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.ho?cpage=1\">동물병원</a></div>\r\n");
      out.write("        ");
 if(loginUser == null && loginHosp == null) { 
      out.write("\r\n");
      out.write("        <!-- 로그인전에 보여지는 로그인 form -->\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/start.pe\">반려동물 관리</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("            <div class=\"menu last\"><a href=\"");
      out.print( contextPath );
      out.write("/loginEnroll.us\" class=\"last\">로그인/회원가입</a></div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 } else if(loginUser != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if(loginUser.getMemberId().equals("admin")) { 
      out.write("\r\n");
      out.write("            <!--  관리자로 로그인시 로그인 form -->\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.mem?cpage=1\">관리자페이지</a></div>\r\n");
      out.write("		        <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("		            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginUser.getMemberName() );
      out.write("</p>\r\n");
      out.write("		            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px; \" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("		        </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else {  
      out.write("\r\n");
      out.write("            <!-- 개인회원 로그인 시 로그인 form -->\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/start.pe\">반려동물 관리</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/myPage.us\">마이페이지</a></div>\r\n");
      out.write("                <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("		            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginUser.getMemberName() );
      out.write("</p>\r\n");
      out.write("		            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px;\" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("		        </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } else if(loginHosp != null) { 
      out.write("\r\n");
      out.write("		<!-- 병원회원 로그인 시 로그인 form -->\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/hospitalPage.ho?hospId=");
      out.print( loginHosp.getHospId() );
      out.write("\">동물병원 관리</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/myPage.us\">마이페이지</a></div>\r\n");
      out.write("            <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("	            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginHosp.getHospName() );
      out.write("</p>\r\n");
      out.write("	            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px;\" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("	        </div>       \r\n");
      out.write("        ");
 } 
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"content\">\r\n");
      out.write("      <div class=\"content_1\">\r\n");
      out.write("        <div id=\"communityPageMenu\">커뮤니티</div>\r\n");
      out.write("         <ul class=\"nav\">                          \r\n");
      out.write("            <li id=\"chat\">									\r\n");
      out.write("               	<a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\" id=\"wagle\" class=\"wagle\"; >와글와글게시판</a>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("            <li id=\"questionboard\">\r\n");
      out.write("             			<a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=60\" id=\"question\" class=\"question\";>질문게시판</a> \r\n");
      out.write("             			\r\n");
      out.write("\r\n");
      out.write("             			\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"content_2\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("         <h2 id='wag' class=wag>");
      out.print( list.get(0).getCategory());
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div id=\"writeBtn\" style=\"width:850px;\">\r\n");
      out.write("			<!--  로그인한 회원만 보여지는 버튼 : loginUser가 null인지 아닌지 판단 -->\r\n");
      out.write("			");
 if((loginUser != null) || (loginHosp !=null)) { 
      out.write("\r\n");
      out.write("			<a id='write'href=\"");
      out.print( contextPath );
      out.write("/enrollForm.bo\" class=\"btn btn-info btn-sm\">글작성</a>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<table class=\"list-area\" align=\"center\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"70\">글번호</th>\r\n");
      out.write("					<th width=\"70\">카테고리</th>\r\n");
      out.write("					<th width=\"300\">제목</th>\r\n");
      out.write("					<th width=\"100\">작성자</th>\r\n");
      out.write("					<th width=\"50\">조회수</th>\r\n");
      out.write("					<th width=\"100\">작성일</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 게시글 출력 : 게시글이 있는지 없는지 => inEmpty() -->\r\n");
      out.write("				\r\n");
      out.write("				");
 if(list.isEmpty()) { 
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"6\">조회된 게시글이 없습니다.</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("					<!-- 반복문 : list에 있는 값을 순차적으로 접근해서 뽑아오기 -->\r\n");
      out.write("					");
 for(Community c : list) { 
      out.write("\r\n");
      out.write("						<tr class='llist'>\r\n");
      out.write("							<td>");
      out.print( c.getCommNo() );
      out.write("</td>\r\n");
      out.write("							<td width = \"150px\">");
      out.print( c.getCategory() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( c.getCommTitle().substring(0, 12) );
      out.write(". . .</td>\r\n");
      out.write("							<td>");
      out.print( c.getCommWriter() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( c.getCount() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( c.getCreateDate() );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("         <script>\r\n");
      out.write("		\r\n");
      out.write("         $(function(){\r\n");
      out.write("        	\r\n");
      out.write("        	 \r\n");
      out.write("        	 ");
 if(list.get(0).getCategory().equals("와글와글게시판")) { 
      out.write("\r\n");
      out.write("     	 		$('#question').removeClass('question');\r\n");
      out.write("     	 	");
 } else {
      out.write("\r\n");
      out.write("     	 		$('#wagle').removeClass('wagle');\r\n");
      out.write("     	 	");
 } 
      out.write("\r\n");
      out.write("         $(\"#question\").click(function() {\r\n");
      out.write("        	 \r\n");
      out.write("        	 $('#wagle').removeClass('wagle');\r\n");
      out.write("        	  	 \r\n");
      out.write("        	 })\r\n");
      out.write(" 	 \r\n");
      out.write("         })\r\n");
      out.write("			$(function(){\r\n");
      out.write("	\r\n");
      out.write("				$(\".list-area>tbody>tr\").click(function(){\r\n");
      out.write("		\r\n");
      out.write("					\r\n");
      out.write("					var ccno = $(this).children().eq(0).text();\r\n");
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("					// \"쿼리 스트링\" : ? 뒤의 내용들, 직접 쿼리스트링을 만들어서 요청\r\n");
      out.write("					\r\n");
      out.write("							\r\n");
      out.write("					location.href=\"");
      out.print(contextPath);
      out.write("/detail.bo?ccno=\"+ccno;\r\n");
      out.write("					\r\n");
      out.write("	\r\n");
      out.write("				})\r\n");
      out.write("	\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("		<br><br>\r\n");
      out.write("		\r\n");
      out.write("		");
if(list.get(0).getCategory().equals("와글와글게시판")) {
      out.write("\r\n");
      out.write("		<div align=\"center\" class=\"paging-area\">\r\n");
      out.write("			");
 if(currentPage != 1) { 
      out.write("  <!-- 페이징바에서 <를 담당 -->\r\n");
      out.write("			<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print( currentPage-1 );
      out.write("&cno=50'\"> &lt; </button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			");
 for(int i = startPage; i <= endPage; i++) { 
      out.write("\r\n");
      out.write("				");
 if(i != currentPage) { 
      out.write("\r\n");
      out.write("				<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print(i );
      out.write("&cno=50'\" >");
      out.print( i );
      out.write("</button>\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("					<button class=\"btn btn-info\" disabled>");
      out.print( i );
      out.write("</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			");
 if(currentPage != maxPage) { 
      out.write("\r\n");
      out.write("			<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print( currentPage+1 );
      out.write("&cno=50'\"> &gt; </button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } else if(list.get(0).getCategory().equals("질문게시판")){ 
      out.write("\r\n");
      out.write("            <div align=\"center\" class=\"paging-area\">\r\n");
      out.write("			");
 if(currentPage != 1) { 
      out.write("  <!-- 페이징바에서 <를 담당 -->\r\n");
      out.write("			<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print( currentPage-1 );
      out.write("&cno=60'\"> &lt; </button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			");
 for(int i = startPage; i <= endPage; i++) { 
      out.write("\r\n");
      out.write("				");
 if(i != currentPage) { 
      out.write("\r\n");
      out.write("				<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print(i );
      out.write("&cno=60'\" >");
      out.print( i );
      out.write("</button>\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("					<button class=\"btn btn-info\" disabled>");
      out.print( i );
      out.write("</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			");
 if(currentPage != maxPage) { 
      out.write("\r\n");
      out.write("			<button class=\"btn btn-info\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=");
      out.print( currentPage+1 );
      out.write("&cno=60'\"> &gt; </button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("      	\r\n");
      out.write("      	");
 } 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"content_3\"></div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <br clear=\"both\"><br><br><br>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>푸터~</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #footer {\r\n");
      out.write("        background-color: rgb(241, 241, 241);\r\n");
      out.write("        color: rgb(158, 158, 158);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer_1 {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer_2 {\r\n");
      out.write("        font-size: 11px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div id=\"footer_1\">\r\n");
      out.write("            <br>\r\n");
      out.write("            상호 : (주)펫티스트 <br>\r\n");
      out.write("            대표 : 최벼리 <br>\r\n");
      out.write("            사업자등록번호 : XXX-XX-XXXX <br>\r\n");
      out.write("            주소 : 승철특별시 원석구 성준로 131(성수빌딩) 최승희호 <br>\r\n");
      out.write("            개인정보관리 책임자 : 정유진 younng369@naver.com <br>\r\n");
      out.write("            대표전화  : 02-XXX-XXXX <br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer_2\">\r\n");
      out.write("            <br>\r\n");
      out.write("            Copyright © 이정도면잘했조 All Rights Reserved.\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
