/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-10 18:06:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.user.model.vo.*;
import com.kh.user.model.vo.Hospital;

public final class userEnrollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1657460402856L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1657460402857L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.kh.user.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.user.model.vo.Hospital");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petist-회원가입</title>\r\n");
      out.write("<link href=\"/Petist/resources/common/logo_mint.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<style>\r\n");
      out.write("    #login-header{\r\n");
      out.write("        background-color: rgb(26, 188, 156);\r\n");
      out.write("        height: 15%;\r\n");
      out.write("    }\r\n");
      out.write("    #login-form{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    #login-form tr,td{\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        padding-bottom: 5px;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #login-form table{\r\n");
      out.write("        width: 55%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("    }\r\n");
      out.write("    .box{\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #buttonbox button{\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        height: 150px; \r\n");
      out.write("        display:inline-block;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        background-color: rgb(26, 188, 156);\r\n");
      out.write("        border: none;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	Hospital loginHosp = (Hospital)session.getAttribute("loginHosp");

	String alertMsg = (String)session.getAttribute("alertMsg");
	
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    .nav-area { background-color: rgb(26, 188, 156); height: 78px; }\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        height: 76px;\r\n");
      out.write("        width: auto;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a, .menu button {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 16px; \r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu button {\r\n");
      out.write("        background-color: rgb(26, 188, 156);\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #logo:hover { cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write("    #petist { \r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        vertical-align: center;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    #photo {\r\n");
      out.write("        padding-left: 15px;\r\n");
      out.write("        padding-right: 15px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu a:hover { text-decoration: underline; text-underline-position: under; text-decoration-thickness: 4px; font-size: 18px; }\r\n");
      out.write("\r\n");
      out.write("    .last { padding-right: 40px; padding-left: 40px; }\r\n");
      out.write("\r\n");
      out.write("    img { width: 55px; height: 55px; }\r\n");
      out.write("    \r\n");
      out.write("    div {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .content {\r\n");
      out.write("    	width: 1200px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content > div, .content_short > div {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        margin-bottom: 30px;    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content_short {\r\n");
      out.write("    	width: 1200px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .content_1 {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    .content_2 {\r\n");
      out.write("    	width: 80%;\r\n");
      out.write("    }\r\n");
      out.write("    .content_3 {\r\n");
      out.write("    	width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    div {\r\n");
      out.write("    	box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("		\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\" ){\r\n");
      out.write("			Swal.fire({\r\n");
      out.write("				  title: 'Petist',\r\n");
      out.write("				  text: msg,\r\n");
      out.write("				  imageUrl: '/Petist/resources/common/logo_mint.png',\r\n");
      out.write("				  imageWidth: 130,\r\n");
      out.write("				  imageHeight: 110,\r\n");
      out.write("				  confirmButtonText: '확인',\r\n");
      out.write("				  confirmButtonColor: '#1abc9c'\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"nav-area\" align=\"right\">\r\n");
      out.write("        <div class=\"menu\" id=\"logo\" style=\"float:left;\" onclick='location.href=\"");
      out.print( contextPath );
      out.write("\";'>\r\n");
      out.write("            <div class=\"menu\" id=\"photo\">\r\n");
      out.write("                <img src=\"/Petist/resources/common/logo.png\" alt=\"로고\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <span id=\"petist\" class=\"menu\">Petist</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("\">HOME</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.ho?cpage=1\">동물병원</a></div>\r\n");
      out.write("        ");
 if(loginUser == null && loginHosp == null) { 
      out.write("\r\n");
      out.write("        <!-- 로그인전에 보여지는 로그인 form -->\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/start.pe\">반려동물 관리</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("            <div class=\"menu last\"><a href=\"");
      out.print( contextPath );
      out.write("/loginEnroll.us\" class=\"last\">로그인/회원가입</a></div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 } else if(loginUser != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if(loginUser.getMemberId().equals("admin")) { 
      out.write("\r\n");
      out.write("            <!--  관리자로 로그인시 로그인 form -->\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.mem?cpage=1\">관리자페이지</a></div>\r\n");
      out.write("		        <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("		            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginUser.getMemberName() );
      out.write("</p>\r\n");
      out.write("		            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px; \" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("		        </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else {  
      out.write("\r\n");
      out.write("            <!-- 개인회원 로그인 시 로그인 form -->\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/start.pe\">반려동물 관리</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("                <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/myPage.us\">마이페이지</a></div>\r\n");
      out.write("                <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("		            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginUser.getMemberName() );
      out.write("</p>\r\n");
      out.write("		            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px;\" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("		        </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } else if(loginHosp != null) { 
      out.write("\r\n");
      out.write("		<!-- 병원회원 로그인 시 로그인 form -->\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1&cno=50\">커뮤니티</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no?cpage=1\">공지사항</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/hospitalPage.ho?hospId=");
      out.print( loginHosp.getHospId() );
      out.write("\">동물병원 관리</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/myPage.us\">마이페이지</a></div>\r\n");
      out.write("            <div class=\"menu last\" style=\"vertical-align: top;\">\r\n");
      out.write("	            <p style=\"margin-top: 20px; margin-bottom: 0px; color: white;\">");
      out.print( loginHosp.getHospName() );
      out.write("</p>\r\n");
      out.write("	            <a style=\"padding-bottom: 30px; padding-top: 0; height: 30px;\" href=\"");
      out.print( contextPath );
      out.write("/logout.us\">로그아웃</a>\r\n");
      out.write("	        </div>       \r\n");
      out.write("        ");
 } 
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"content_1\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content_2\">\r\n");
      out.write("			<div id=\"login-form\" >\r\n");
      out.write("				<table style=\"border: 1px solid rgb(198, 197, 197)\" align=\"center\">\r\n");
      out.write("					\r\n");
      out.write("					<tr id=\"login-header\">\r\n");
      out.write("						<td width=\"58px\"><img src=\"/Petist/resources/common/logo.png\" alt=\"로고\"></td>\r\n");
      out.write("						<td class=\"box\">회원가입</td>\r\n");
      out.write("						<td width=\"58px\"> </td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td id=\"buttonbox\" colspan=\"3\"> \r\n");
      out.write("                                <button type=\"button\" onclick=\"memberEnrollPage();\" class=\"box\">개인<br>회원가입</button>\r\n");
      out.write("                                <button type=\"button\" onclick=\"hospEnrollPage();\" class=\"box\">병원<br>회원가입</button>\r\n");
      out.write("							<br>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content_3\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    <script>\r\n");
      out.write("		function memberEnrollPage(){\r\n");
      out.write("			location.href = \"");
      out.print( contextPath );
      out.write("/selectMember.us\";\r\n");
      out.write("		}\r\n");
      out.write("		function hospEnrollPage(){\r\n");
      out.write("			location.href = \"");
      out.print( contextPath );
      out.write("/selectHosp.us\";\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\"><br><br>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>푸터~</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #footer {\r\n");
      out.write("        background-color: rgb(241, 241, 241);\r\n");
      out.write("        color: rgb(158, 158, 158);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer_1 {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer_2 {\r\n");
      out.write("        font-size: 11px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div id=\"footer_1\">\r\n");
      out.write("            <br>\r\n");
      out.write("            상호 : (주)펫티스트 <br>\r\n");
      out.write("            대표 : 최벼리 <br>\r\n");
      out.write("            사업자등록번호 : XXX-XX-XXXX <br>\r\n");
      out.write("            주소 : 승철특별시 원석구 성준로 131(성수빌딩) 최승희호 <br>\r\n");
      out.write("            개인정보관리 책임자 : 정유진 younng369@naver.com <br>\r\n");
      out.write("            대표전화  : 02-XXX-XXXX <br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer_2\">\r\n");
      out.write("            <br>\r\n");
      out.write("            Copyright © 이정도면잘했조 All Rights Reserved.\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
